### ISSUE TITLE
Tasks for @NAnguiano for Week of 9/19

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#36]
Here are the tasks for @NAnguiano for this week (in order):
- [x] Issue #31 branch clean-up
- [ ] Issue #33 repository housekeeping
- [ ] Issue #34 re-create the GODB files using xsd-to-db and update documentation for this
- [ ] Issue #20 once that is all done, re-export a gdb for Vibrio using updated 2016 files
- [x] Issue #37: prep journal club for next Monday

**Comment by kdahlquist** [comment]
moved open tasks to issue #40, so closing this one.
