### ISSUE TITLE
Tasks for @NAnguiano for Week of 10/3

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#40]
Here are the tasks for @NAnguiano for this week (in order):
- [ ] Issue #33 repository housekeeping (needs to wait for some other tasks to be finished first before this can be completed)
- [x] Issue #34 re-create the GODB files using xsd-to-db and update documentation for this; needs to write-up the issues that arose last week so that @dondi can advise
- [x] Issue #20 once that is all done, re-export a gdb for Vibrio using updated 2016 files; this is waiting for #34 to be resolved.

**Comment by kdahlquist** [comment]
Closing this one and moving remaining tasks to new issue. #44
