### ISSUE TITLE
Tasks for @NAnguiano for Week of 10/31 and 11/7

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#44]
Tasks for @NAnguiano 
- [x] #43 Convert web site to Jekyll (pending @dondi's answer to question about gh-pages)
- [ ] #42 write documentation on how to update GMBuilder to work with new OBO-XML files and run schema spy

Tasks for @kdahlquist
- [ ] #20 review requested.
- [ ] #33: ReadMe at top level review requested

**Comment by kdahlquist** [comment]
open issues moved to #47.
