### ISSUE TITLE
Tasks for Week of 11/14 and 11/21

### ISSUE THREAD

**Issue by kdahlquist** [lmu-bioinformatics/xmlpipedb#47]
Tasks for @NAnguiano 
- [x] #46 run schema spy (once documentation is done, this can be closed)
- [x] <s> #30 updates to publications page of website based on @kdahlquist's cv </s>
- [x] #48 prepare PowerPoint presentation for Monday, 11/28, 3:45, LSB 118
- [x] #49 final deliverables and report are due Friday, 12/9 by 5:00 PM.  See issue for details.

Tasks for @kdahlquist
- [ ] #20 review requested.
- [ ] #33: ReadMe at top level review requested

Task for @dondi 
- [ ] #45 redirect xmlpipedb website to github version

**Comment by kdahlquist** [comment]
Extending this to-do list for one more week.  Once the schema spy documentation is done, #46 can be closed.  We are cancelling #30 as a task for @NAnguiano.

Reminder to @dondi to redirect the xmlpipedb web site #45.

@NAnguiano will prepare a PowerPoint presentation #48 to be given at the GRNsight team meeting on Monday, 11/28 at 3:45 in LSB 118.

**Comment by dondi** [comment]
Ah yes…I will be able to look into the redirect this week. Last week and this weekend was a grading binge to get mildly caught up…or I guess the better phrase is “to get a little less behind.” :-P

**Comment by kdahlquist** [comment]
Closing out the semester--@kdahlquist still needs to do the review requested's, but those are described in other issues.
